
dist: trusty

before_install:
  - .ci/setup.sh

install:
  - .ci/install.sh

before_script:
  - .ci/seed_es_on_travis.sh

script:
  - .ci/test.sh

matrix:
  include:
    ############
    # R builds #
    ############
    - language: r
      warnings_are_errors: true
      cache: packages
      env:
        - ES_VERSION=1.0.0
        - TASK=rpkg
    - language: r
      warnings_are_errors: true
      cache: packages
      env:
        - ES_VERSION=1.7.5
        - TASK=rpkg
    - language: r
      warnings_are_errors: true
      cache: packages
      env:
        - ES_VERSION=2.4.2
        - TASK=rpkg
    - language: r
      warnings_are_errors: true
      cache: packages
      env:
        - ES_VERSION=5.6.16
        - TASK=rpkg
    - language: r
      warnings_are_errors: true
      cache: packages
      env:
        - ES_VERSION=6.0.1
        - TASK=rpkg
    - language: r
      warnings_are_errors: true
      cache: packages
      env:
        - ES_VERSION=6.8.2
        - TASK=rpkg
    - language: r
      warnings_are_errors: true
      cache: packages
      env:
        - ES_VERSION=7.0.1
        - TASK=rpkg
    - language: r
      warnings_are_errors: true
      cache: packages
      env:
        - ES_VERSION=7.1.1
        - TASK=rpkg
    - language: r
      warnings_are_errors: true
      cache: packages
      env:
        - ES_VERSION=7.2.1
        - TASK=rpkg
    - language: r
      warnings_are_errors: true
      cache: packages
      env:
        - ES_VERSION=7.3.1
        - TASK=rpkg
      after_success:
        - .ci/report_to_covr.sh
    #################
    # Python builds #
    #################
    - language: python
      python: 3.5
      env:
        - ES_VERSION=1.0.0
        - TASK=pypkg
    - language: python
      python: 3.5
      env:
        - ES_VERSION=1.7.5
        - TASK=pypkg
    - language: python
      python: 3.5
      env:
        - ES_VERSION=2.4.2
        - TASK=pypkg
    - language: python
      python: 3.5
      env:
        - ES_VERSION=5.6.16
        - TASK=pypkg
    - language: python
      python: 3.5
      env:
        - ES_VERSION=6.0.1
        - TASK=pypkg
    - language: python
      python: 3.5
      env:
        - ES_VERSION=6.8.2
        - TASK=pypkg
    - language: python
      python: 3.5
      env:
        - ES_VERSION=7.0.1
        - TASK=pypkg
    - language: python
      python: 3.5
      env:
        - ES_VERSION=7.1.1
        - TASK=pypkg
    - language: python
      python: 3.5
      env:
        - ES_VERSION=7.2.1
        - TASK=pypkg
    - language: python
      python: 3.5
      env:
        - ES_VERSION=7.3.1
        - TASK=pypkg
