
dist: trusty

before_install:
  - .ci/setup.sh

install:
  - .ci/install.sh

before_script:
  - .ci/seed_es_on_travis.sh

script:
  - .ci/test.sh

# Manually specifying each build configuration.
# Would be better to figure out how to build a matrix with two
# languages but share the ES_VERSION matrix across all builds.
# - ES_VERSION=1.0.0
# - ES_VERSION=1.4.4
# - ES_VERSION=1.7.2
# - ES_VERSION=2.0.2
# - ES_VERSION=2.1.2
# - ES_VERSION=2.2.2
# - ES_VERSION=2.3.5
# - ES_VERSION=5.0.2
# - ES_VERSION=5.3.3
# - ES_VERSION=5.4.3
# - ES_VERSION=5.6.9
# - ES_VERSION=6.0.1
# - ES_VERSION=6.1.4
# - ES_VERSION=6.2.4
# - ES_VERSION=7.3.1
matrix:
  include:
    ############
    # R builds #
    ############
    - language: r
      warnings_are_errors: true
      cache: packages
      env:
        - ES_VERSION=1.0.0
        - TASK=rpkg
    - language: r
      warnings_are_errors: true
      cache: packages
      env:
        - ES_VERSION=1.4.4
        - TASK=rpkg
    - language: r
      warnings_are_errors: true
      cache: packages
      env:
        - ES_VERSION=1.7.2
        - TASK=rpkg
    - language: r
      warnings_are_errors: true
      cache: packages
      env:
        - ES_VERSION=2.0.2
        - TASK=rpkg
    - language: r
      warnings_are_errors: true
      cache: packages
      env:
        - ES_VERSION=2.1.2
        - TASK=rpkg
    - language: r
      warnings_are_errors: true
      cache: packages
      env:
        - ES_VERSION=2.2.2
        - TASK=rpkg
    - language: r
      warnings_are_errors: true
      cache: packages
      env:
        - ES_VERSION=2.3.5
        - TASK=rpkg
    - language: r
      warnings_are_errors: true
      cache: packages
      env:
        - ES_VERSION=5.0.2
        - TASK=rpkg
    - language: r
      warnings_are_errors: true
      cache: packages
      env:
        - ES_VERSION=5.3.3
        - TASK=rpkg
    - language: r
      warnings_are_errors: true
      cache: packages
      env:
        - ES_VERSION=5.4.3
        - TASK=rpkg
    - language: r
      warnings_are_errors: true
      cache: packages
      env:
        - ES_VERSION=5.6.9
        - TASK=rpkg
    - language: r
      warnings_are_errors: true
      cache: packages
      env:
        - ES_VERSION=6.0.1
        - TASK=rpkg
    - language: r
      warnings_are_errors: true
      cache: packages
      env:
        - ES_VERSION=6.1.4
        - TASK=rpkg
    - language: r
      warnings_are_errors: true
      cache: packages
      env:
        - ES_VERSION=6.2.4
        - TASK=rpkg
    - language: r
      warnings_are_errors: true
      cache: packages
      env:
        - ES_VERSION=7.3.1
        - TASK=rpkg
      after_success:
        - .ci/report_to_covr.sh
    #################
    # Python builds #
    #################
    - language: python
      python: 3.5
      env:
        - ES_VERSION=1.0.0
        - TASK=pypkg
    - language: python
      python: 3.5
      env:
        - ES_VERSION=1.4.4
        - TASK=pypkg
    - language: python
      python: 3.5
      env:
        - ES_VERSION=1.7.2
        - TASK=pypkg
    - language: python
      python: 3.5
      env:
        - ES_VERSION=2.0.2
        - TASK=pypkg
    - language: python
      python: 3.5
      env:
        - ES_VERSION=2.1.2
        - TASK=pypkg
    - language: python
      python: 3.5
      env:
        - ES_VERSION=2.2.2
        - TASK=pypkg
    - language: python
      python: 3.5
      env:
        - ES_VERSION=2.3.5
        - TASK=pypkg
    - language: python
      python: 3.5
      env:
        - ES_VERSION=5.0.2
        - TASK=pypkg
    - language: python
      python: 3.5
      env:
        - ES_VERSION=5.3.3
        - TASK=pypkg
    - language: python
      python: 3.5
      env:
        - ES_VERSION=5.4.3
        - TASK=pypkg
    - language: python
      python: 3.5
      env:
        - ES_VERSION=5.6.9
        - TASK=pypkg
    - language: python
      python: 3.5
      env:
        - ES_VERSION=6.0.1
        - TASK=pypkg
    - language: python
      python: 3.5
      env:
        - ES_VERSION=6.1.4
        - TASK=pypkg
    - language: python
      python: 3.5
      env:
        - ES_VERSION=6.2.4
        - TASK=pypkg
    - language: python
      python: 3.5
      env:
        - ES_VERSION=7.3.1
        - TASK=pypkg
