name: Tests

on: [push]

jobs:
  test:
    name: ${{ matrix.task }} (ES ${{ matrix.es_version }})
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        include:
          - task: rpkg
            es_version: 1.0.3
          - task: rpkg
            es_version: 1.7.6
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 1
      - name: Setup R
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: '4.0.3'
      - name: Set up Python
        uses: conda-incubator/setup-miniconda@v1.7.0
        with:
          python-version: ${{ matrix.python_version }}
      - name: Setup and run tests
        shell: bash
        run: |
          export CONDA_DIR=${HOME}/miniconda3
          export ES_VERSION=${{ matrix.es_version }}
          export PATH=${CONDA_DIR}/bin:${HOME}/.local/bin:$PATH
          export TASK="${{ matrix.task }}"
          $GITHUB_WORKSPACE/.ci/setup.sh
          $GITHUB_WORKSPACE/.ci/install.sh
          $GITHUB_WORKSPACE/.ci/setup_local.sh ${{ matrix.es_version }}
          $GITHUB_WORKSPACE/.ci/test.sh
          codecov
  # https://github.community/t/is-it-possible-to-require-all-github-actions-tasks-to-pass-without-enumerating-them/117957/4?u=graingert
  all-successful:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
    - name: Note that all tests succeeded
      run: echo "🎉"
